name: example
publish_to: "none"

environment:
  sdk: ^3.0.5

dependencies:
  zef_di_core: ^5.0.0
 
  zef_helpers_lazy: ^2.0.0

  # Test dependencies
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

  build_runner:

  zef_di_core_generator:
    path: ../
